import React from 'react';
import {Home,ClipboardList,MessageSquare,Warehouse,ShoppingCart,CreditCard,Users,Facebook,Bot,BarChart3,Settings,Bell,Plus,Search,ChevronLeft,Package,DollarSign,TrendingUp,AlertTriangle,UserRound,Sparkles,Boxes,RefreshCw,Menu,X,Phone,MapPin,Calendar,Hash,Box,Wallet,ArrowUpLeft,ExternalLink,CheckCircle2,Clock3,Truck,Layers3,Activity,ShieldCheck,BrainCircuit,SlidersHorizontal,ChevronRight} from 'lucide-react';

const SUPABASE_URL='https://wqfuovvebgipiowaarbo.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6IndxZnVvdnZlYmdpcGlvd2FhcmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5MTM2ODEsImV4cCI6MjA5NzQ4OTY4MX0.xeQ80kco6TOpbyMnYonzSCBDI3Hn_EKiavKKfC7kLl8';
const H={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const TABLES={orders:'alfhd_orders',conversations:'alfhd_conversations',products:'wh_products',sales:'wh_sales',debts:'wh_debts',employees:'wh_employees',pages:'alfhd_pages',suppliers:'wh_suppliers'};
const NAV=[['home','الرئيسية',Home],['orders','الطلبات',ClipboardList],['conversations','المحادثات',MessageSquare],['warehouse','المخزن',Warehouse],['sales','المبيعات',ShoppingCart],['debts','الديون',CreditCard],['employees','الموظفون',Users],['pages','الصفحات',Facebook],['ai','الذكاء',Bot],['stats','الإحصائيات',BarChart3],['settings','الإعدادات',Settings]];
const BRIDGE={orders:'الطلبات',conversations:'المحادثات',warehouse:'المخزن',stats:'الإحصائيات',employees:'الموظفين',pages:'الصفحات',ai:'الذكاء'};
function session(){try{const r=localStorage.getItem('alfhd_session')||sessionStorage.getItem('alfhd_session');return r?JSON.parse(r):null}catch{return null}}
function val(o,...ks){for(const k of ks){if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=='')return o[k]}return ''}
function money(v){const n=Number(String(v||0).replace(/[^0-9.-]/g,''))||0;return new Intl.NumberFormat('en-US').format(Math.round(n))}
function date(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ar-IQ')}
function statusText(o){return val(o,'status','stage','prep_status','delivery_status')||'جديد'}
function findButton(rx){const els=[...document.querySelectorAll('#root button,#root [role="button"]')];return els.find(x=>rx.test((x.textContent||'').trim()))}
function nativeClick(rx){const b=findButton(rx);b?.click();return !!b}
function nativeSection(id){const l=BRIDGE[id];if(l)nativeClick(new RegExp(l))}
function useMobile(){const[m,setM]=React.useState(()=>innerWidth<900);React.useEffect(()=>{const f=()=>setM(innerWidth<900);addEventListener('resize',f);return()=>removeEventListener('resize',f)},[]);return m}
async function loadTable(table,ws){const p=new URLSearchParams({select:'*',order:'created_at.desc',limit:'150'});if(ws)p.set('workspace_id',`eq.${ws}`);const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${p}`,{headers:H});if(!r.ok)throw new Error(`${table}:${r.status}`);return r.json()}

function IconBox({children}){return <span className="fr2-iconbox">{children}</span>}
function Header({title,sub,icon:Icon=Sparkles,action,onAction}){return <div className="fr2-header"><div><span className="fr2-eyebrow"><Icon size={14}/> ALFHD OS</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="fr2-primary" onClick={onAction}><Plus size={17}/>{action}</button>}</div>}
function Metric({icon:Icon,label,value,sub,tone=''}){return <div className={`fr2-metric ${tone}`}><IconBox><Icon size={18}/></IconBox><small>{label}</small><strong>{value}</strong><em>{sub}</em></div>}
function Empty({title='لا توجد بيانات',sub='ماكو عناصر للعرض حالياً'}){return <div className="fr2-empty"><Boxes size={34}/><b>{title}</b><span>{sub}</span></div>}
function Pill({children,tone=''}){return <span className={`fr2-pill ${tone}`}>{children}</span>}
function SectionTitle({title,sub,action}){return <div className="fr2-section-title"><div><h3>{title}</h3><p>{sub}</p></div>{action}</div>}
function Field({icon:Icon,label,value}){if(value===undefined||value===null||value==='')return null;return <div className="fr2-field"><Icon size={16}/><div><small>{label}</small><b>{String(value)}</b></div></div>}

function DetailDrawer({item,kind,onClose,onNative}){
 if(!item)return null;
 const cfg={
 orders:{title:val(item,'customer_name','customer','phone')||'تفاصيل الطلب',icon:ClipboardList,fields:[['رقم الطلب',val(item,'order_no','fahd_ref','id'),Hash],['الحالة',statusText(item),Activity],['الهاتف',val(item,'phone','customer_phone'),Phone],['العنوان',val(item,'address','location','governorate'),MapPin],['المنتج',val(item,'order_type','product_name','items'),Package],['السعر',val(item,'price','total','amount')?`${money(val(item,'price','total','amount'))} د.ع`:'',Wallet],['التاريخ',date(val(item,'created_at','order_date')),Calendar]]},
 products:{title:val(item,'name','product_name','title')||'تفاصيل المنتج',icon:Package,fields:[['الصنف',val(item,'category','type'),Layers3],['المتوفر',val(item,'quantity','stock','qty'),Box],['السعر',val(item,'price','sale_price')?`${money(val(item,'price','sale_price'))} د.ع`:'',Wallet],['الباركود',val(item,'barcode','sku','code'),Hash],['التاريخ',date(val(item,'created_at')),Calendar]]},
 sales:{title:val(item,'customer_name','customer')||'تفاصيل البيع',icon:ShoppingCart,fields:[['المبلغ',`${money(val(item,'total','amount','price'))} د.ع`,Wallet],['المنتج',val(item,'product_name','notes','item'),Package],['الكمية',val(item,'quantity','qty'),Box],['التاريخ',date(val(item,'created_at','date')),Calendar]]},
 debts:{title:val(item,'customer_name','name')||'تفاصيل الدين',icon:CreditCard,fields:[['المبلغ',`${money(val(item,'amount','remaining','debt'))} د.ع`,Wallet],['الهاتف',val(item,'phone'),Phone],['ملاحظة',val(item,'notes','note'),ClipboardList],['التاريخ',date(val(item,'created_at','date')),Calendar]]},
 employees:{title:val(item,'name','employee_name')||'الموظف',icon:UserRound,fields:[['الدور',val(item,'role','position'),ShieldCheck],['الهاتف',val(item,'phone'),Phone],['الحالة',val(item,'status')||'فعال',Activity],['التاريخ',date(val(item,'created_at')),Calendar]]},
 pages:{title:val(item,'name','page_name')||'الصفحة',icon:Facebook,fields:[['Page ID',val(item,'page_id','id'),Hash],['الحالة',val(item,'status')||'مرتبطة',Activity],['المعرف',val(item,'username','page_username'),Facebook],['التاريخ',date(val(item,'created_at')),Calendar]]},
 suppliers:{title:val(item,'name','supplier_name')||'المورد',icon:Warehouse,fields:[['الهاتف',val(item,'phone'),Phone],['الملاحظات',val(item,'notes','note'),ClipboardList],['التاريخ',date(val(item,'created_at')),Calendar]]}
 }[kind]||{title:'التفاصيل',icon:Package,fields:[]};
 const I=cfg.icon;
 return <div className="fr2-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="fr2-drawer"><div className="fr2-drawer-head"><IconBox><I size={20}/></IconBox><div><small>تفاصيل</small><h2>{cfg.title}</h2></div><button onClick={onClose}><X size={20}/></button></div><div className="fr2-drawer-fields">{cfg.fields.map(([l,v,Icon],i)=><Field key={i} label={l} value={v} icon={Icon}/>)}</div><div className="fr2-raw-note">كل البيانات الوظيفية تبقى من النظام الأصلي؛ هذه الواجهة هي طبقة العرض الجديدة.</div>{onNative&&<button className="fr2-native" onClick={onNative}><ExternalLink size={17}/> فتح الإجراءات الكاملة</button>}</aside></div>
}

function OrderCards({rows,onOpen}){if(!rows.length)return <Empty/>;return <div className="fr2-order-grid">{rows.map((o,i)=><button className="fr2-order" key={o.id||i} onClick={()=>onOpen(o)}><div className="fr2-order-top"><IconBox><ClipboardList size={18}/></IconBox><Pill>{statusText(o)}</Pill></div><h3>{val(o,'customer_name','customer','phone')||'عميل بدون اسم'}</h3><p>{val(o,'order_type','product_name','items')||'طلب'}</p><div className="fr2-order-meta"><span><Phone size={13}/>{val(o,'phone','customer_phone')||'—'}</span><span><MapPin size={13}/>{val(o,'governorate','address','location')||'—'}</span></div><div className="fr2-order-foot"><b>{val(o,'price','total','amount')?`${money(val(o,'price','total','amount'))} د.ع`:'—'}</b><small>{date(val(o,'created_at','order_date'))}</small></div></button>)}</div>}
function RowList({rows,kind,onOpen}){if(!rows.length)return <Empty/>;const cfg={products:[Package,'name','product_name','title'],sales:[ShoppingCart,'customer_name','customer'],debts:[CreditCard,'customer_name','name'],employees:[UserRound,'name','employee_name'],pages:[Facebook,'name','page_name'],suppliers:[Warehouse,'name','supplier_name']}[kind]||[Package,'name'];const I=cfg[0];return <div className="fr2-list">{rows.map((o,i)=><button key={o.id||i} className="fr2-row" onClick={()=>onOpen(o)}><IconBox><I size={18}/></IconBox><div className="fr2-row-main"><b>{val(o,...cfg.slice(1))||`${kind} #${i+1}`}</b><small>{kind==='products'?`المتوفر ${val(o,'quantity','stock','qty')||0}`:kind==='sales'?val(o,'product_name','notes')||'عملية بيع':kind==='debts'?val(o,'phone','notes')||'دين مفتوح':kind==='employees'?val(o,'role','position','phone')||'موظف':kind==='pages'?val(o,'page_id','username')||'Facebook':val(o,'phone','notes')||'مورد'}</small></div><div className="fr2-row-side"><Pill>{kind==='products'?money(val(o,'price','sale_price')):kind==='sales'?`${money(val(o,'total','amount','price'))} د.ع`:kind==='debts'?`${money(val(o,'amount','remaining','debt'))} د.ع`:val(o,'status')||date(val(o,'created_at'))}</Pill><ChevronLeft size={16}/></div></button>)}</div>}

function ConversationView({rows,selected,setSelected,onNative}){if(!rows.length)return <Empty title="لا توجد محادثات"/>;const active=selected||rows[0];return <div className="fr2-chat"><div className="fr2-chat-list">{rows.map((o,i)=><button key={o.id||i} className={active===o?'active':''} onClick={()=>setSelected(o)}><IconBox><MessageSquare size={17}/></IconBox><div><b>{val(o,'customer_name','sender_name','name')||'محادثة'}</b><small>{val(o,'last_message','message','last_text')||'بدون رسالة'}</small></div><em>{date(val(o,'updated_at','created_at'))}</em></button>)}</div><div className="fr2-chat-pane"><div className="fr2-chat-head"><div><small>{val(active,'platform','channel')||'Messenger'}</small><h3>{val(active,'customer_name','sender_name','name')||'محادثة'}</h3></div><button className="fr2-native-inline" onClick={onNative}><ExternalLink size={15}/> فتح الإرسال الفعلي</button></div><div className="fr2-chat-body"><div className="fr2-bubble theirs">{val(active,'last_message','message','last_text')||'لا توجد رسالة أخيرة محفوظة'}<small>{date(val(active,'updated_at','created_at'))}</small></div><div className="fr2-chat-context"><MessageSquare size={30}/><b>مركز محادثات جديد</b><p>المحادثة والعميل والطلب المرتبط يظهرون هنا بدل الانتقال لشاشة قديمة.</p></div></div><div className="fr2-composer"><input readOnly placeholder="الإرسال الفعلي يبقى مربوط بالنظام الأصلي"/><button onClick={onNative}>فتح</button></div></div></div>}

function StatsView({orders,sales,debts,products,conversations}){const revenue=sales.reduce((a,o)=>a+(Number(String(val(o,'total','amount','price')||0).replace(/[^0-9.-]/g,''))||0),0);const max=Math.max(orders.length,sales.length,debts.length,products.length,conversations.length,1);const bars=[['طلبات',orders.length],['مبيعات',sales.length],['ديون',debts.length],['منتجات',products.length],['محادثات',conversations.length]];return <><div className="fr2-metrics"><Metric icon={ClipboardList} label="الطلبات" value={orders.length} sub="إجمالي"/><Metric icon={DollarSign} label="الإيراد" value={`${money(revenue)} د.ع`} sub="مسجل"/><Metric icon={Package} label="المنتجات" value={products.length} sub="صنف"/><Metric icon={MessageSquare} label="المحادثات" value={conversations.length} sub="نشاط"/></div><div className="fr2-chart-card"><SectionTitle title="صورة النشاط" sub="مقارنة مباشرة بين أقسام النظام"/><div className="fr2-bars">{bars.map(([l,v])=><div key={l}><span style={{height:`${Math.max(12,(v/max)*100)}%`}}/><b>{v}</b><small>{l}</small></div>)}</div></div></>}

export default function FullRebuildShellV2(){
 const mobile=useMobile();const[s,setS]=React.useState(()=>session());const[tab,setTab]=React.useState('home');const[menu,setMenu]=React.useState(false);const[data,setData]=React.useState({});const[loading,setLoading]=React.useState(false);const[q,setQ]=React.useState('');const[detail,setDetail]=React.useState(null);const[warehouseTab,setWarehouseTab]=React.useState('products');const[selectedConv,setSelectedConv]=React.useState(null);
 React.useEffect(()=>{const t=setInterval(()=>setS(session()),700);return()=>clearInterval(t)},[]);
 const user=s?.userData||{};const ws=user.workspaceId||user.workspace_id||null;
 const refresh=React.useCallback(async()=>{if(!s)return;setLoading(true);const pairs=await Promise.all(Object.entries(TABLES).map(async([k,t])=>{try{return[k,await loadTable(t,ws)]}catch{return[k,[]]}}));setData(Object.fromEntries(pairs));setLoading(false)},[s,ws]);
 React.useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[refresh]);
 if(!s)return null;
 const orders=data.orders||[],products=data.products||[],sales=data.sales||[],debts=data.debts||[],employees=data.employees||[],conversations=data.conversations||[],pages=data.pages||[],suppliers=data.suppliers||[];
 const revenue=sales.reduce((a,o)=>a+(Number(String(val(o,'total','amount','price')||0).replace(/[^0-9.-]/g,''))||0),0);const debtTotal=debts.reduce((a,o)=>a+(Number(String(val(o,'amount','remaining','debt')||0).replace(/[^0-9.-]/g,''))||0),0);
 const filtered=(rows)=>!q?rows:rows.filter(o=>JSON.stringify(o).toLowerCase().includes(q.toLowerCase()));
 const select=id=>{setTab(id);setMenu(false);setDetail(null)};
 const newOrder=()=>nativeClick(/طلب جديد|إضافة طلب/);const openNative=id=>nativeSection(id);
 return <div className="fr2-root" dir="rtl">
  {!mobile&&<aside className="fr2-side"><div className="fr2-brand"><div>ف</div><span><b>ALFHD</b><small>OPERATIONS OS</small></span></div><nav>{NAV.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I size={18}/><span>{label}</span>{tab===id&&<i/>}</button>)}</nav><div className="fr2-user"><div>{String(user.name||'فهد')[0]}</div><span><b>{user.name||'فهد'}</b><small>{user.role||'مدير النظام'}</small></span></div></aside>}
  <main className="fr2-main"><header className="fr2-top"><button className="fr2-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="fr2-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث داخل القسم الحالي..."/></div><button className="fr2-icon" onClick={()=>nativeClick(/إشعار|الإشعارات/)}><Bell size={18}/><i/></button><button className="fr2-icon" onClick={refresh}><RefreshCw size={17} className={loading?'spin':''}/></button></header>
  {mobile&&menu&&<div className="fr2-mobile-menu">{NAV.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I size={18}/><span>{label}</span></button>)}</div>}
  <section className="fr2-page">
   {tab==='home'&&<><Header title={`مرحبا ${user.name||'فهد'} 👋`} sub="لوحة تشغيل جديدة بالكامل، مو ثيم فوق القديم."/><div className="fr2-hero"><div><span className="fr2-eyebrow"><Sparkles size={14}/> PREMIUM OPERATIONS</span><h2>كل شغلك صار تجربة وحدة.</h2><p>طلبات، زبائن، مخزن، مبيعات وذكاء داخل نظام بصري موحّد وسريع.</p><div className="fr2-hero-actions"><button className="fr2-primary" onClick={newOrder}><Plus size={17}/> طلب جديد</button><button className="fr2-secondary" onClick={()=>select('conversations')}><MessageSquare size={17}/> المحادثات</button></div></div><div className="fr2-sphere"><span/><b>ALFHD</b></div></div><div className="fr2-metrics"><Metric icon={ClipboardList} label="الطلبات" value={orders.length} sub="إجمالي"/><Metric icon={MessageSquare} label="المحادثات" value={conversations.length} sub="نشاط العملاء"/><Metric icon={DollarSign} label="المبيعات" value={`${money(revenue)} د.ع`} sub="إجمالي مسجل"/><Metric icon={AlertTriangle} label="الديون" value={`${money(debtTotal)} د.ع`} sub="مفتوحة"/></div><SectionTitle title="آخر الطلبات" sub="آخر النشاطات داخل النظام" action={<button onClick={()=>select('orders')}>عرض الكل <ChevronLeft size={14}/></button>}/><OrderCards rows={orders.slice(0,6)} onOpen={o=>setDetail({kind:'orders',item:o})}/></>}
   {tab==='orders'&&<><Header title="الطلبات" sub="واجهة طلبات جديدة من الصفر: قراءة أسرع وتفاصيل أوضح." icon={ClipboardList} action="طلب جديد" onAction={newOrder}/><div className="fr2-metrics"><Metric icon={ClipboardList} label="الإجمالي" value={orders.length} sub="طلب"/><Metric icon={Clock3} label="قيد العمل" value={orders.filter(o=>!String(statusText(o)).match(/مكتمل|ملغي|تم/)).length} sub="نشط"/><Metric icon={CheckCircle2} label="منتهي" value={orders.filter(o=>String(statusText(o)).match(/مكتمل|تم/)).length} sub="مكتمل"/><Metric icon={Truck} label="توصيل" value={orders.filter(o=>String(statusText(o)).match(/شحن|توصيل|مندوب/)).length} sub="بالطريق"/></div><OrderCards rows={filtered(orders)} onOpen={o=>setDetail({kind:'orders',item:o})}/></>}
   {tab==='conversations'&&<><Header title="المحادثات" sub="تجربة رسائل جديدة داخل نفس النظام، مو صفحة Telegram القديمة." icon={MessageSquare}/><ConversationView rows={filtered(conversations)} selected={selectedConv} setSelected={setSelectedConv} onNative={()=>openNative('conversations')}/></>}
   {tab==='warehouse'&&<><Header title="المخزن" sub="مركز واحد للمنتجات والموردين مع تفاصيل حديثة." icon={Warehouse} action="إضافة منتج" onAction={()=>{openNative('warehouse');setTimeout(()=>nativeClick(/إضافة منتج|منتج جديد/),120)}}/><div className="fr2-metrics"><Metric icon={Package} label="المنتجات" value={products.length} sub="صنف"/><Metric icon={Warehouse} label="الموردون" value={suppliers.length} sub="مورد"/><Metric icon={AlertTriangle} label="منخفض" value={products.filter(o=>Number(val(o,'quantity','stock','qty')||0)<5).length} sub="أقل من 5"/></div><div className="fr2-tabs"><button className={warehouseTab==='products'?'active':''} onClick={()=>setWarehouseTab('products')}>المنتجات</button><button className={warehouseTab==='suppliers'?'active':''} onClick={()=>setWarehouseTab('suppliers')}>الموردون</button></div>{warehouseTab==='products'?<RowList rows={filtered(products)} kind="products" onOpen={o=>setDetail({kind:'products',item:o})}/>:<RowList rows={filtered(suppliers)} kind="suppliers" onOpen={o=>setDetail({kind:'suppliers',item:o})}/>}</>}
   {tab==='sales'&&<><Header title="المبيعات" sub="الإيرادات والعمليات بتسلسل بصري جديد." icon={ShoppingCart} action="عملية بيع" onAction={()=>{openNative('warehouse');setTimeout(()=>nativeClick(/بيع جديد|عملية بيع/),120)}}/><div className="fr2-metrics"><Metric icon={ShoppingCart} label="العمليات" value={sales.length} sub="بيع"/><Metric icon={DollarSign} label="الإيراد" value={`${money(revenue)} د.ع`} sub="إجمالي"/></div><RowList rows={filtered(sales)} kind="sales" onOpen={o=>setDetail({kind:'sales',item:o})}/></>}
   {tab==='debts'&&<><Header title="الديون" sub="متابعة الديون المفتوحة بدون جداول قديمة مزدحمة." icon={CreditCard}/><div className="fr2-metrics"><Metric icon={CreditCard} label="السجلات" value={debts.length} sub="دين"/><Metric icon={Wallet} label="الإجمالي" value={`${money(debtTotal)} د.ع`} sub="مفتوح"/></div><RowList rows={filtered(debts)} kind="debts" onOpen={o=>setDetail({kind:'debts',item:o})}/></>}
   {tab==='employees'&&<><Header title="الموظفون" sub="بطاقات موظفين واضحة بدل الشاشة القديمة." icon={Users} action="إضافة موظف" onAction={()=>{openNative('employees');setTimeout(()=>nativeClick(/إضافة موظف|موظف جديد/),120)}}/><div className="fr2-people-grid">{filtered(employees).length?filtered(employees).map((o,i)=><button key={o.id||i} className="fr2-person" onClick={()=>setDetail({kind:'employees',item:o})}><div className="fr2-avatar">{String(val(o,'name','employee_name')||'م')[0]}</div><h3>{val(o,'name','employee_name')||'موظف'}</h3><p>{val(o,'role','position')||'موظف'}</p><Pill>{val(o,'status')||'فعال'}</Pill></button>):<Empty/>}</div></>}
   {tab==='pages'&&<><Header title="الصفحات" sub="إدارة قنوات فيسبوك كتكاملات واضحة وحديثة." icon={Facebook} action="ربط صفحة" onAction={()=>{openNative('pages');setTimeout(()=>nativeClick(/ربط|إضافة صفحة/),120)}}/><div className="fr2-integration-grid">{filtered(pages).length?filtered(pages).map((o,i)=><button className="fr2-integration" key={o.id||i} onClick={()=>setDetail({kind:'pages',item:o})}><div className="fr2-integration-logo"><Facebook size={25}/></div><div><small>FACEBOOK PAGE</small><h3>{val(o,'name','page_name')||'صفحة'}</h3><p>{val(o,'page_id','username')||'قناة مرتبطة'}</p></div><Pill>{val(o,'status')||'مرتبطة'}</Pill></button>):<Empty/>}</div></>}
   {tab==='ai'&&<><Header title="الذكاء" sub="مركز تحكم بصري للردود والتشغيل الذكي." icon={Bot}/><div className="fr2-ai-hero"><div className="fr2-ai-logo"><BrainCircuit size={34}/></div><div><span className="fr2-eyebrow">AI OPERATIONS</span><h2>مركز الذكاء التشغيلي</h2><p>راقب المحادثات والطلبات وافتح إعدادات الذكاء الفعلية من مكان واحد.</p></div><button className="fr2-primary" onClick={()=>openNative('ai')}><SlidersHorizontal size={17}/> إعدادات الذكاء</button></div><div className="fr2-metrics"><Metric icon={MessageSquare} label="محادثات" value={conversations.length} sub="قابل للمعالجة"/><Metric icon={ClipboardList} label="طلبات" value={orders.length} sub="سياق الطلبات"/><Metric icon={Activity} label="الحالة" value="فعال" sub="المحرك متصل"/></div><div className="fr2-settings-grid"><button onClick={()=>openNative('ai')}><Bot/><b>سياسة الرد</b><span>افتح إعدادات الردود الحالية</span></button><button onClick={()=>openNative('conversations')}><MessageSquare/><b>صندوق الرسائل</b><span>راجع المحادثات الحقيقية</span></button><button onClick={()=>select('stats')}><BarChart3/><b>الأداء</b><span>شاهد مؤشرات النظام</span></button></div></>}
   {tab==='stats'&&<><Header title="الإحصائيات" sub="قراءة بصرية حديثة لأهم أرقام النظام." icon={BarChart3}/><StatsView orders={orders} sales={sales} debts={debts} products={products} conversations={conversations}/></>}
   {tab==='settings'&&<><Header title="الإعدادات" sub="مركز إعدادات جديد بدل القوائم المتفرقة." icon={Settings}/><div className="fr2-settings-grid"><button onClick={()=>openNative('pages')}><Facebook/><b>قنوات التواصل</b><span>الصفحات والربط</span></button><button onClick={()=>openNative('employees')}><Users/><b>المستخدمون</b><span>الموظفون والصلاحيات</span></button><button onClick={()=>openNative('ai')}><Bot/><b>إعدادات الذكاء</b><span>الردود والمعالجة</span></button><button onClick={()=>openNative('warehouse')}><Warehouse/><b>المخزن</b><span>المنتجات والموردون</span></button><button onClick={()=>nativeClick(/إشعار|الإشعارات/)}><Bell/><b>الإشعارات</b><span>التنبيهات الحالية</span></button><button onClick={refresh}><RefreshCw/><b>تحديث البيانات</b><span>مزامنة فورية</span></button></div></>}
  </section>
  {mobile&&<nav className="fr2-bottom">{[['home','الرئيسية',Home],['orders','الطلبات',ClipboardList],['conversations','المحادثات',MessageSquare],['warehouse','المخزن',Warehouse],['settings','المزيد',Menu]].map(([id,l,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I size={19}/><span>{l}</span></button>)}</nav>}
  </main>
  {detail&&<DetailDrawer item={detail.item} kind={detail.kind} onClose={()=>setDetail(null)} onNative={()=>{const map={orders:'orders',products:'warehouse',suppliers:'warehouse',employees:'employees',pages:'pages',sales:'warehouse',debts:'warehouse'};openNative(map[detail.kind]);}}/>
 </div>
}
