import React from 'react';
import {Home,MessageSquare,Package,Users,Search,Plus,BarChart3,Truck,Sparkles,Bot,Phone,MapPin,Calendar,RefreshCw,Warehouse,ShoppingCart,CreditCard,DollarSign,TrendingUp,Bell,Clock,AlertTriangle,Facebook,Menu,X,FileText,CheckCircle2,ChevronDown,ArrowRight,ShieldCheck} from 'lucide-react';

const SUPABASE_URL='https://wqfuovvebgipiowaarbo.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZnVvdnZlYmdpcGlvd2FhcmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5MTM2ODEsImV4cCI6MjA5NzQ4OTY4MX0.xeQ80kco6TOpbyMnYonzSCBDI3Hn_EKiavKKfC7kLl8';
const H={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const TABLES={orders:'alfhd_orders',conversations:'alfhd_conversations',products:'wh_products',sales:'wh_sales',debts:'wh_debts',employees:'wh_employees',pages:'alfhd_pages',suppliers:'wh_suppliers'};
const NAV=[['home','الرئيسية',Home],['orders','الطلبات',FileText],['conversations','المحادثات',MessageSquare],['warehouse','المخزن',Warehouse],['sales','المبيعات',ShoppingCart],['debts','الديون',CreditCard],['employees','الموظفون',Users],['pages','الصفحات',Facebook],['ai','الذكاء',Bot],['stats','الإحصائيات',BarChart3],['settings','الإعدادات',ShieldCheck]];
const BRIDGE={orders:'الطلبات',conversations:'المحادثات',warehouse:'المخزن',stats:'الإحصائيات',employees:'الموظفين',pages:'الصفحات',ai:'الذكاء'};
function sess(){try{const r=localStorage.getItem('alfhd_session')||sessionStorage.getItem('alfhd_session');return r?JSON.parse(r):null}catch{return null}}
function v(o,...ks){for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=='')return o[k];return ''}
function cash(x){const n=Number(String(x||0).replace(/[^0-9.-]/g,''))||0;return new Intl.NumberFormat('en-US').format(Math.round(n))}
function dte(x){if(!x)return '—';const d=new Date(x);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ar-IQ')}
function native(rx){const b=[...document.querySelectorAll('#root button,#root [role="button"]')].find(e=>rx.test((e.textContent||'').trim()));b?.click();return !!b}
function openSection(id){if(BRIDGE[id])native(new RegExp(BRIDGE[id]))}
function mobileHook(){const[m,setM]=React.useState(()=>innerWidth<900);React.useEffect(()=>{const f=()=>setM(innerWidth<900);addEventListener('resize',f);return()=>removeEventListener('resize',f)},[]);return m}
async function load(table,ws){const p=new URLSearchParams({select:'*',order:'created_at.desc',limit:'150'});if(ws)p.set('workspace_id',`eq.${ws}`);const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${p}`,{headers:H});if(!r.ok){const body=await r.text();throw new Error(`${table}:${r.status}:${body}`)}return r.json()}
function status(o){return v(o,'status','stage','prep_status','delivery_status')||'جديد'}
function Icon({children}){return <span className="fr2-iconbox">{children}</span>}
function Head({title,sub,icon:I=Sparkles,action,onAction}){return <div className="fr2-header"><div><span className="fr2-eyebrow"><I size={14}/> ALFHD OS</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="fr2-primary" onClick={onAction}><Plus size={17}/>{action}</button>}</div>}
function Metric({I,label,value,sub}){return <div className="fr2-metric"><Icon><I size={18}/></Icon><small>{label}</small><strong>{value}</strong><em>{sub}</em></div>}
function Empty(){return <div className="fr2-empty"><Package size={34}/><b>لا توجد بيانات</b><span>ماكو عناصر للعرض حالياً</span></div>}
function Pill({children}){return <span className="fr2-pill">{children}</span>}
function Section({title,sub,children}){return <><div className="fr2-section-title"><div><h3>{title}</h3><p>{sub}</p></div></div>{children}</>}
function filtered(rows,q){if(!q)return rows;const z=q.toLowerCase();return rows.filter(o=>JSON.stringify(o).toLowerCase().includes(z))}

function Orders({rows,onOpen}){if(!rows.length)return <Empty/>;return <div className="fr2-order-grid">{rows.map((o,i)=><button className="fr2-order" key={o.id||i} onClick={()=>onOpen('orders',o)}><div className="fr2-order-top"><Icon><FileText size={18}/></Icon><Pill>{status(o)}</Pill></div><h3>{v(o,'customer_name','customer','phone')||'عميل بدون اسم'}</h3><p>{v(o,'order_type','product_name','items')||'طلب'}</p><div className="fr2-order-meta"><span><Phone size={13}/>{v(o,'phone','customer_phone')||'—'}</span><span><MapPin size={13}/>{v(o,'governorate','address','location')||'—'}</span></div><div className="fr2-order-foot"><b>{v(o,'price','total','amount')?`${cash(v(o,'price','total','amount'))} د.ع`:'—'}</b><small>{dte(v(o,'created_at','order_date'))}</small></div></button>)}</div>}
const kinds={products:{I:Package,name:['name','product_name','title'],sub:o=>`المتوفر: ${v(o,'quantity','stock','qty')||0}`,side:o=>cash(v(o,'price','sale_price'))},sales:{I:ShoppingCart,name:['customer_name','customer'],sub:o=>v(o,'product_name','notes')||'عملية بيع',side:o=>`${cash(v(o,'total','amount','price'))} د.ع`},debts:{I:CreditCard,name:['customer_name','name'],sub:o=>v(o,'phone','notes')||'دين مفتوح',side:o=>`${cash(v(o,'amount','remaining','debt'))} د.ع`},employees:{I:Users,name:['name','employee_name'],sub:o=>v(o,'role','position','phone')||'موظف',side:o=>v(o,'status')||'فعال'},pages:{I:Facebook,name:['name','page_name'],sub:o=>v(o,'page_id','username')||'Facebook',side:o=>v(o,'status')||'مرتبطة'},suppliers:{I:Warehouse,name:['name','supplier_name'],sub:o=>v(o,'phone','notes')||'مورد',side:o=>dte(v(o,'created_at'))}};
function Rows({rows,kind,onOpen}){if(!rows.length)return <Empty/>;const c=kinds[kind];const I=c.I;return <div className="fr2-list">{rows.map((o,i)=><button className="fr2-row" key={o.id||i} onClick={()=>onOpen(kind,o)}><Icon><I size={18}/></Icon><div className="fr2-row-main"><b>{v(o,...c.name)||`${kind} #${i+1}`}</b><small>{c.sub(o)}</small></div><div className="fr2-row-side"><Pill>{c.side(o)}</Pill><ArrowRight size={15}/></div></button>)}</div>}
function Detail({state,onClose,onNative}){if(!state)return null;const {kind,o}=state;const title=kind==='orders'?v(o,'customer_name','customer','phone'):kind==='products'?v(o,'name','product_name','title'):kind==='sales'?v(o,'customer_name','customer'):kind==='debts'?v(o,'customer_name','name'):kind==='employees'?v(o,'name','employee_name'):kind==='pages'?v(o,'name','page_name'):v(o,'name','supplier_name');const fields=kind==='orders'?[['الحالة',status(o),Clock],['الهاتف',v(o,'phone','customer_phone'),Phone],['العنوان',v(o,'address','location','governorate'),MapPin],['المنتج',v(o,'order_type','product_name','items'),Package],['السعر',v(o,'price','total','amount')?`${cash(v(o,'price','total','amount'))} د.ع`:'',DollarSign],['التاريخ',dte(v(o,'created_at','order_date')),Calendar]]:kind==='products'?[['المتوفر',v(o,'quantity','stock','qty'),Package],['السعر',`${cash(v(o,'price','sale_price'))} د.ع`,DollarSign],['الصنف',v(o,'category','type'),FileText]]:kind==='sales'?[['المبلغ',`${cash(v(o,'total','amount','price'))} د.ع`,DollarSign],['المنتج',v(o,'product_name','notes'),Package],['التاريخ',dte(v(o,'created_at','date')),Calendar]]:kind==='debts'?[['المبلغ',`${cash(v(o,'amount','remaining','debt'))} د.ع`,CreditCard],['الهاتف',v(o,'phone'),Phone],['التاريخ',dte(v(o,'created_at','date')),Calendar]]:kind==='employees'?[['الدور',v(o,'role','position'),Users],['الهاتف',v(o,'phone'),Phone],['الحالة',v(o,'status')||'فعال',CheckCircle2]]:kind==='pages'?[['Page ID',v(o,'page_id','id'),Facebook],['الحالة',v(o,'status')||'مرتبطة',CheckCircle2],['المعرف',v(o,'username'),Facebook]]:[['الهاتف',v(o,'phone'),Phone],['الملاحظات',v(o,'notes'),FileText]];return <div className="fr2-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="fr2-drawer"><div className="fr2-drawer-head"><Icon><FileText size={20}/></Icon><div><small>تفاصيل</small><h2>{title||'التفاصيل'}</h2></div><button onClick={onClose}><X size={20}/></button></div><div className="fr2-drawer-fields">{fields.filter(x=>x[1]!==''&&x[1]!==undefined).map(([l,z,I],i)=><div className="fr2-field" key={i}><I size={16}/><div><small>{l}</small><b>{String(z)}</b></div></div>)}</div><div className="fr2-raw-note">الواجهة جديدة بالكامل، بينما الحفظ والتعديل يبقون مربوطين بمنطق النظام الأصلي.</div><button className="fr2-native" onClick={onNative}>فتح الإجراءات الأصلية</button></aside></div>}
function Chat({rows,onNative}){const[sel,setSel]=React.useState(null);if(!rows.length)return <Empty/>;const a=sel||rows[0];return <div className="fr2-chat"><div className="fr2-chat-list">{rows.map((o,i)=><button className={a===o?'active':''} key={o.id||i} onClick={()=>setSel(o)}><Icon><MessageSquare size={17}/></Icon><div><b>{v(o,'customer_name','sender_name','name')||'محادثة'}</b><small>{v(o,'last_message','message','last_text')||'بدون رسالة'}</small></div><em>{dte(v(o,'updated_at','created_at'))}</em></button>)}</div><div className="fr2-chat-pane"><div className="fr2-chat-head"><div><small>{v(a,'platform','channel')||'Messenger'}</small><h3>{v(a,'customer_name','sender_name','name')||'محادثة'}</h3></div><button className="fr2-native-inline" onClick={onNative}>فتح الإرسال</button></div><div className="fr2-chat-body"><div className="fr2-bubble">{v(a,'last_message','message','last_text')||'لا توجد رسالة أخيرة'}<small>{dte(v(a,'updated_at','created_at'))}</small></div><div className="fr2-chat-context"><MessageSquare size={30}/><b>مركز محادثة جديد</b><p>المحادثة صارت داخل نفس لغة الواجهة الجديدة.</p></div></div><div className="fr2-composer"><input readOnly placeholder="الإرسال الفعلي مربوط بالنظام الحالي"/><button onClick={onNative}>فتح</button></div></div></div>}
function Stats({orders,sales,debts,products,conversations}){const revenue=sales.reduce((a,o)=>a+(Number(String(v(o,'total','amount','price')||0).replace(/[^0-9.-]/g,''))||0),0);const arr=[['طلبات',orders.length],['مبيعات',sales.length],['ديون',debts.length],['منتجات',products.length],['محادثات',conversations.length]],mx=Math.max(...arr.map(x=>x[1]),1);return <><div className="fr2-metrics"><Metric I={FileText} label="الطلبات" value={orders.length} sub="إجمالي"/><Metric I={DollarSign} label="الإيراد" value={`${cash(revenue)} د.ع`} sub="مسجل"/><Metric I={Package} label="المنتجات" value={products.length} sub="صنف"/><Metric I={MessageSquare} label="المحادثات" value={conversations.length} sub="نشاط"/></div><div className="fr2-chart-card"><Section title="صورة النشاط" sub="مقارنة مباشرة بين الأقسام"><div className="fr2-bars">{arr.map(([l,z])=><div key={l}><span style={{height:`${Math.max(12,z/mx*100)}%`}}/><b>{z}</b><small>{l}</small></div>)}</div></Section></div></>}

export default function FullRebuildShellV3(){const mobile=mobileHook();const[s,setS]=React.useState(()=>sess());const[tab,setTab]=React.useState('home');const[menu,setMenu]=React.useState(false);const[data,setData]=React.useState({});const[loading,setLoading]=React.useState(false);const[q,setQ]=React.useState('');const[detail,setDetail]=React.useState(null);const[wtab,setWtab]=React.useState('products');React.useEffect(()=>{const t=setInterval(()=>setS(sess()),700);return()=>clearInterval(t)},[]);const user=s?.userData||{},ws=user.workspaceId||user.workspace_id||null;const refresh=React.useCallback(async()=>{if(!s)return;setLoading(true);const entries=await Promise.all(Object.entries(TABLES).map(async([k,t])=>{try{return[k,await load(t,ws),null]}catch(err){console.error('FullRebuild load failed',k,err);return[k,null,err]}}));setData(prev=>{const next={...prev};for(const [k,rows,err] of entries){if(!err)next[k]=rows}return next});setLoading(false)},[s,ws]);React.useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[refresh]);if(!s)return null;const orders=data.orders||[],conversations=data.conversations||[],products=data.products||[],sales=data.sales||[],debts=data.debts||[],employees=data.employees||[],pages=data.pages||[],suppliers=data.suppliers||[];const revenue=sales.reduce((a,o)=>a+(Number(String(v(o,'total','amount','price')||0).replace(/[^0-9.-]/g,''))||0),0),debt=debts.reduce((a,o)=>a+(Number(String(v(o,'amount','remaining','debt')||0).replace(/[^0-9.-]/g,''))||0),0);const F=rows=>filtered(rows,q),select=id=>{setTab(id);setMenu(false);setDetail(null)},open=(kind,o)=>setDetail({kind,o});return <div className="fr2-root" dir="rtl">{!mobile&&<aside className="fr2-side"><div className="fr2-brand"><div>ف</div><span><b>ALFHD</b><small>OPERATIONS OS</small></span></div><nav>{NAV.map(([id,l,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I size={18}/><span>{l}</span>{tab===id&&<i/>}</button>)}</nav><div className="fr2-user"><div>{String(user.name||'فهد')[0]}</div><span><b>{user.name||'فهد'}</b><small>{user.role||'مدير النظام'}</small></span></div></aside>}<main className="fr2-main"><header className="fr2-top"><button className="fr2-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="fr2-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث داخل القسم..."/></div><button className="fr2-icon" onClick={()=>native(/إشعار|الإشعارات/)}><Bell size={18}/><i/></button><button className="fr2-icon" onClick={refresh}><RefreshCw size={17} className={loading?'spin':''}/></button></header>{mobile&&menu&&<div className="fr2-mobile-menu">{NAV.map(([id,l,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I/><span>{l}</span></button>)}</div>}<section className="fr2-page">
{tab==='home'&&<><Head title={`مرحبا ${user.name||'فهد'} 👋`} sub="إعادة بناء كاملة لكل النظام بنفس هوية الرئيسية."/><div className="fr2-hero"><div><span className="fr2-eyebrow"><Sparkles size={14}/> PREMIUM OPERATIONS</span><h2>كل قسم صار جزء من تجربة وحدة.</h2><p>ماكو شاشة قديمة ظاهرة كقسم رئيسي؛ كل شيء مبني بنفس النظام البصري الجديد.</p><div className="fr2-hero-actions"><button className="fr2-primary" onClick={()=>native(/طلب جديد|إضافة طلب/)}><Plus/> طلب جديد</button><button className="fr2-secondary" onClick={()=>select('conversations')}><MessageSquare/> المحادثات</button></div></div><div className="fr2-sphere"><span/><b>ALFHD</b></div></div><div className="fr2-metrics"><Metric I={FileText} label="الطلبات" value={orders.length} sub="إجمالي"/><Metric I={MessageSquare} label="المحادثات" value={conversations.length} sub="نشاط"/><Metric I={DollarSign} label="المبيعات" value={`${cash(revenue)} د.ع`} sub="مسجل"/><Metric I={AlertTriangle} label="الديون" value={`${cash(debt)} د.ع`} sub="مفتوحة"/></div><Section title="آخر الطلبات" sub="آخر النشاطات"><Orders rows={orders.slice(0,6)} onOpen={open}/></Section></>}
{tab==='orders'&&<><Head title="الطلبات" sub="بطاقات وتفاصيل جديدة بالكامل." icon={FileText} action="طلب جديد" onAction={()=>native(/طلب جديد|إضافة طلب/)}/><div className="fr2-metrics"><Metric I={FileText} label="الإجمالي" value={orders.length} sub="طلب"/><Metric I={Clock} label="قيد العمل" value={orders.filter(o=>!String(status(o)).match(/مكتمل|ملغي|تم/)).length} sub="نشط"/><Metric I={CheckCircle2} label="مكتمل" value={orders.filter(o=>String(status(o)).match(/مكتمل|تم/)).length} sub="منتهي"/><Metric I={Truck} label="توصيل" value={orders.filter(o=>String(status(o)).match(/شحن|توصيل|مندوب/)).length} sub="بالطريق"/></div><Orders rows={F(orders)} onOpen={open}/></>}
{tab==='conversations'&&<><Head title="المحادثات" sub="صندوق رسائل جديد ضمن نفس التطبيق." icon={MessageSquare}/><Chat rows={F(conversations)} onNative={()=>openSection('conversations')}/></>}
{tab==='warehouse'&&<><Head title="المخزن" sub="منتجات وموردون بتجربة جديدة." icon={Warehouse} action="إضافة منتج" onAction={()=>{openSection('warehouse');setTimeout(()=>native(/إضافة منتج|منتج جديد/),120)}}/><div className="fr2-metrics"><Metric I={Package} label="المنتجات" value={products.length} sub="صنف"/><Metric I={Warehouse} label="الموردون" value={suppliers.length} sub="مورد"/><Metric I={AlertTriangle} label="منخفض" value={products.filter(o=>Number(v(o,'quantity','stock','qty')||0)<5).length} sub="يحتاج متابعة"/></div><div className="fr2-tabs"><button className={wtab==='products'?'active':''} onClick={()=>setWtab('products')}>المنتجات</button><button className={wtab==='suppliers'?'active':''} onClick={()=>setWtab('suppliers')}>الموردون</button></div>{wtab==='products'?<Rows rows={F(products)} kind="products" onOpen={open}/>:<Rows rows={F(suppliers)} kind="suppliers" onOpen={open}/>}</>}
{tab==='sales'&&<><Head title="المبيعات" sub="عمليات البيع والإيراد بشكل جديد." icon={ShoppingCart} action="عملية بيع" onAction={()=>{openSection('warehouse');setTimeout(()=>native(/بيع جديد|عملية بيع/),120)}}/><div className="fr2-metrics"><Metric I={ShoppingCart} label="العمليات" value={sales.length} sub="عملية"/><Metric I={DollarSign} label="الإيراد" value={`${cash(revenue)} د.ع`} sub="إجمالي"/></div><Rows rows={F(sales)} kind="sales" onOpen={open}/></>}
{tab==='debts'&&<><Head title="الديون" sub="متابعة واضحة للديون المفتوحة." icon={CreditCard}/><div className="fr2-metrics"><Metric I={CreditCard} label="السجلات" value={debts.length} sub="دين"/><Metric I={DollarSign} label="الإجمالي" value={`${cash(debt)} د.ع`} sub="مفتوح"/></div><Rows rows={F(debts)} kind="debts" onOpen={open}/></>}
{tab==='employees'&&<><Head title="الموظفون" sub="إدارة الفريق ضمن نفس الهوية." icon={Users} action="إضافة موظف" onAction={()=>{openSection('employees');setTimeout(()=>native(/إضافة موظف|موظف جديد/),120)}}/><Rows rows={F(employees)} kind="employees" onOpen={open}/></>}
{tab==='pages'&&<><Head title="الصفحات" sub="قنوات فيسبوك كتكاملات حديثة." icon={Facebook} action="ربط صفحة" onAction={()=>{openSection('pages');setTimeout(()=>native(/ربط|إضافة صفحة/),120)}}/><Rows rows={F(pages)} kind="pages" onOpen={open}/></>}
{tab==='ai'&&<><Head title="الذكاء" sub="مركز تشغيل بصري للردود الذكية." icon={Bot}/><div className="fr2-ai-hero"><div className="fr2-ai-logo"><Bot size={34}/></div><div><span className="fr2-eyebrow">AI OPERATIONS</span><h2>مركز الذكاء التشغيلي</h2><p>المحادثات والطلبات والإعدادات من نفس الواجهة.</p></div><button className="fr2-primary" onClick={()=>openSection('ai')}>إعدادات الذكاء</button></div><div className="fr2-settings-grid"><button onClick={()=>openSection('ai')}><Bot/><b>سياسة الرد</b><span>إعدادات الذكاء الحالية</span></button><button onClick={()=>select('conversations')}><MessageSquare/><b>المحادثات</b><span>مراجعة رسائل العملاء</span></button><button onClick={()=>select('stats')}><BarChart3/><b>الأداء</b><span>مؤشرات التشغيل</span></button></div></>}
{tab==='stats'&&<><Head title="الإحصائيات" sub="لوحة أرقام ورسوم جديدة." icon={BarChart3}/><Stats orders={orders} sales={sales} debts={debts} products={products} conversations={conversations}/></>}
{tab==='settings'&&<><Head title="الإعدادات" sub="مركز واحد لكل إعدادات النظام." icon={ShieldCheck}/><div className="fr2-settings-grid"><button onClick={()=>openSection('pages')}><Facebook/><b>القنوات</b><span>الصفحات والربط</span></button><button onClick={()=>openSection('employees')}><Users/><b>المستخدمون</b><span>الموظفون والصلاحيات</span></button><button onClick={()=>openSection('ai')}><Bot/><b>الذكاء</b><span>الردود والمعالجة</span></button><button onClick={()=>openSection('warehouse')}><Warehouse/><b>المخزن</b><span>المنتجات والموردون</span></button><button onClick={()=>native(/إشعار|الإشعارات/)}><Bell/><b>الإشعارات</b><span>مركز التنبيهات</span></button><button onClick={refresh}><RefreshCw/><b>المزامنة</b><span>تحديث البيانات الآن</span></button></div></>}
</section>{mobile&&<nav className="fr2-bottom">{[['home','الرئيسية',Home],['orders','الطلبات',FileText],['conversations','المحادثات',MessageSquare],['warehouse','المخزن',Warehouse],['settings','المزيد',Menu]].map(([id,l,I])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><I/><span>{l}</span></button>)}</nav>}</main>{detail&&<Detail state={detail} onClose={()=>setDetail(null)} onNative={()=>{const m={orders:'orders',products:'warehouse',suppliers:'warehouse',sales:'warehouse',debts:'warehouse',employees:'employees',pages:'pages'};openSection(m[detail.kind])}}/>}</div>}
