import React from 'react';
import { Home, ClipboardList, MessageSquare, Warehouse, ShoppingCart, CreditCard, Users, Facebook, Bot, BarChart3, Settings, Bell, Plus, Search, ChevronLeft, Package, DollarSign, TrendingUp, AlertTriangle, UserRound, Sparkles, Boxes, RefreshCw, Menu, X } from 'lucide-react';

const SUPABASE_URL='https://wqfuovvebgipiowaarbo.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6IndxZnVvdnZlYmdpcGlvd2FhcmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5MTM2ODEsImV4cCI6MjA5NzQ4OTY4MX0.xeQ80kco6TOpbyMnYonzSCBDI3Hn_EKiavKKfC7kLl8';
const H={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
const TABLES={orders:'alfhd_orders',conversations:'alfhd_conversations',products:'wh_products',sales:'wh_sales',debts:'wh_debts',employees:'wh_employees',pages:'alfhd_pages',suppliers:'wh_suppliers'};
const NAV=[
 ['home','الرئيسية',Home],['orders','الطلبات',ClipboardList],['conversations','المحادثات',MessageSquare],['warehouse','المخزن',Warehouse],['sales','المبيعات',ShoppingCart],['debts','الديون',CreditCard],['employees','الموظفون',Users],['pages','الصفحات',Facebook],['ai','الذكاء',Bot],['stats','الإحصائيات',BarChart3],['settings','الإعدادات',Settings]
];
const BRIDGE_LABELS={orders:'الطلبات',conversations:'المحادثات',warehouse:'المخزن',stats:'الإحصائيات',employees:'الموظفين',pages:'الصفحات',ai:'الذكاء'};
function session(){try{const r=localStorage.getItem('alfhd_session')||sessionStorage.getItem('alfhd_session');return r?JSON.parse(r):null}catch{return null}}
function val(o,...keys){for(const k of keys){if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=='')return o[k]}return ''}
function money(v){const n=Number(String(v||0).replace(/[^0-9.-]/g,''))||0;return new Intl.NumberFormat('en-US').format(Math.round(n))}
function date(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ar-IQ')}
function clickNative(label){const els=[...document.querySelectorAll('#root button,#root [role="button"]')];const b=els.find(x=>(x.textContent||'').trim().includes(label));b?.click();return !!b}
function openNativeSection(id){const l=BRIDGE_LABELS[id];if(l)clickNative(l)}
function nativeAction(pattern){const els=[...document.querySelectorAll('#root button')];const b=els.find(x=>pattern.test((x.textContent||'').trim()));b?.click();return !!b}
function useMobile(){const[m,setM]=React.useState(()=>innerWidth<900);React.useEffect(()=>{const f=()=>setM(innerWidth<900);addEventListener('resize',f);return()=>removeEventListener('resize',f)},[]);return m}
async function loadTable(table,ws){const p=new URLSearchParams({select:'*',order:'created_at.desc',limit:'100'});if(ws)p.set('workspace_id',`eq.${ws}`);const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${p}`,{headers:H});if(!r.ok)throw new Error(`${table}:${r.status}`);return r.json()}

function Metric({icon:Icon,label,value,sub}){return <div className="fr-metric"><span><Icon size={18}/></span><small>{label}</small><strong>{value}</strong><em>{sub}</em></div>}
function Header({title,sub,action,onAction,icon:Icon=Sparkles}){return <div className="fr-header"><div><span className="fr-eyebrow"><Icon size={14}/> ALFHD WORKSPACE</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="fr-primary" onClick={onAction}><Plus size={18}/>{action}</button>}</div>}
function Empty({text}){return <div className="fr-empty"><Boxes size={34}/><b>{text}</b><span>ماكو بيانات للعرض حالياً</span></div>}
function ListCard({title,sub,badge,meta,onClick,icon:Icon=Package}){return <button className="fr-list-card" onClick={onClick}><span className="fr-list-icon"><Icon size={20}/></span><div className="fr-list-copy"><b>{title||'بدون اسم'}</b><small>{sub||'—'}</small></div>{badge&&<span className="fr-badge">{badge}</span>}<em>{meta||''}</em><ChevronLeft size={17}/></button>}
function DataGrid({rows,kind,onOpen}){if(!rows.length)return <Empty text="لا توجد بيانات"/>;return <div className="fr-grid">{rows.map((o,i)=>{
 const configs={
 orders:[val(o,'order_type','product_name','items')||'طلب',val(o,'customer_name','customer','phone')||'عميل',val(o,'status','stage','prep_status')||'جديد',val(o,'order_no','fahd_ref')||`#${i+1}`,ClipboardList],
 conversations:[val(o,'customer_name','sender_name','name')||'محادثة',val(o,'last_message','message','last_text')||'بدون رسالة',val(o,'platform','channel')||'Messenger',date(val(o,'updated_at','created_at')),MessageSquare],
 products:[val(o,'name','product_name','title')||'منتج',`المتوفر: ${val(o,'quantity','stock','qty')||0}`,val(o,'category')||'مخزن',money(val(o,'price','sale_price')),Package],
 sales:[val(o,'customer_name','customer')||'عملية بيع',val(o,'product_name','notes')||'بيع',money(val(o,'total','amount','price')),date(val(o,'created_at','date')),ShoppingCart],
 debts:[val(o,'customer_name','name')||'دين',val(o,'phone','notes')||'—',money(val(o,'amount','remaining','debt')),date(val(o,'created_at','date')),CreditCard],
 employees:[val(o,'name','employee_name')||'موظف',val(o,'role','position','phone')||'—',val(o,'status')||'فعال',date(val(o,'created_at')),UserRound],
 pages:[val(o,'name','page_name')||'صفحة',val(o,'page_id','username')||'Facebook',val(o,'status')||'مرتبطة',date(val(o,'created_at')),Facebook],
 suppliers:[val(o,'name','supplier_name')||'مورد',val(o,'phone','notes')||'—','مورد',date(val(o,'created_at')),Warehouse]
 };
 const c=configs[kind]||configs.orders;return <ListCard key={o.id||i} title={c[0]} sub={c[1]} badge={c[2]} meta={c[3]} icon={c[4]} onClick={()=>onOpen?.(o)}/>})}</div>}

export default function FullRebuildShell(){
 const mobile=useMobile();const[s,setS]=React.useState(()=>session());const[tab,setTab]=React.useState('home');const[menu,setMenu]=React.useState(false);const[data,setData]=React.useState({});const[loading,setLoading]=React.useState(false);const[q,setQ]=React.useState('');
 React.useEffect(()=>{const t=setInterval(()=>setS(session()),700);return()=>clearInterval(t)},[]);
 const user=s?.userData||{};const ws=user.workspaceId||user.workspace_id||null;
 const refresh=React.useCallback(async()=>{if(!s)return;setLoading(true);const pairs=await Promise.all(Object.entries(TABLES).map(async([k,t])=>{try{return[k,await loadTable(t,ws)]}catch{return[k,[]]}}));setData(Object.fromEntries(pairs));setLoading(false)},[s,ws]);
 React.useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[refresh]);
 if(!s)return null;
 const orders=data.orders||[],products=data.products||[],sales=data.sales||[],debts=data.debts||[],employees=data.employees||[],conversations=data.conversations||[];
 const revenue=sales.reduce((a,o)=>a+(Number(String(val(o,'total','amount','price')||0).replace(/[^0-9.-]/g,''))||0),0);
 const debtTotal=debts.reduce((a,o)=>a+(Number(String(val(o,'amount','remaining','debt')||0).replace(/[^0-9.-]/g,''))||0),0);
 const filterRows=(rows)=>!q?rows:rows.filter(o=>JSON.stringify(o).toLowerCase().includes(q.toLowerCase()));
 const select=(id)=>{setTab(id);setMenu(false)};
 const openDetail=(id)=>openNativeSection(id);
 return <div className="fr-root" dir="rtl">
  {!mobile&&<aside className="fr-side"><div className="fr-brand"><div>ف</div><span><b>ALFHD</b><small>Operations OS</small></span></div><nav>{NAV.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><Icon size={19}/><span>{label}</span>{tab===id&&<i/>}</button>)}</nav><div className="fr-user"><div>{String(user.name||'فهد')[0]}</div><span><b>{user.name||'فهد'}</b><small>{user.role||'مدير النظام'}</small></span></div></aside>}
  <main className="fr-main">
   <div className="fr-topbar"><button className="fr-mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="fr-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث داخل النظام..."/></div><button className="fr-icon" onClick={()=>nativeAction(/إشعار|الإشعارات/)}><Bell size={19}/><i/></button><button className="fr-icon" onClick={refresh}><RefreshCw size={18} className={loading?'spin':''}/></button></div>
   {mobile&&menu&&<div className="fr-mobile-sheet">{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>select(id)} className={tab===id?'active':''}><Icon/><span>{label}</span></button>)}</div>}
   <section className="fr-page">
    {tab==='home'&&<><Header title={`مرحبا ${user.name||'فهد'} 👋`} sub="كل عملياتك بمكان واحد، بسرعة ووضوح."/><div className="fr-hero"><div><small>نظام العمليات الذكي</small><h2>إدارة أسرع. تفاصيل أوضح. شغل أهدأ.</h2><p>الطلبات، المحادثات، المخزن والمبيعات كلها مرتبطة بنفس الواجهة.</p><button onClick={()=>select('orders')}>عرض الطلبات <ChevronLeft/></button></div><div className="fr-orb"><span/><b>ALFHD</b></div></div><div className="fr-metrics"><Metric icon={ClipboardList} label="إجمالي الطلبات" value={orders.length} sub="كل الطلبات"/><Metric icon={MessageSquare} label="المحادثات" value={conversations.length} sub="قنوات العملاء"/><Metric icon={DollarSign} label="المبيعات" value={`${money(revenue)} د.ع`} sub="إجمالي مسجل"/><Metric icon={AlertTriangle} label="الديون" value={`${money(debtTotal)} د.ع`} sub="المبالغ المفتوحة"/></div><div className="fr-section-head"><div><h3>آخر الطلبات</h3><p>أحدث النشاطات المسجلة</p></div><button onClick={()=>select('orders')}>عرض الكل</button></div><DataGrid rows={orders.slice(0,6)} kind="orders" onOpen={()=>openDetail('orders')}/></>}
    {tab==='orders'&&<><Header title="الطلبات" sub="إدارة الطلبات من أول تسجيل إلى التسليم." action="طلب جديد" onAction={()=>nativeAction(/طلب جديد|إضافة طلب/)} icon={ClipboardList}/><div className="fr-metrics"><Metric icon={Package} label="إجمالي" value={orders.length} sub="طلب"/><Metric icon={TrendingUp} label="نشط" value={orders.filter(o=>!o.converted).length} sub="قيد العمل"/><Metric icon={ClipboardList} label="مؤرشف" value={orders.filter(o=>o.converted).length} sub="مكتمل"/></div><DataGrid rows={filterRows(orders)} kind="orders" onOpen={()=>openDetail('orders')}/></>}
    {tab==='conversations'&&<><Header title="المحادثات" sub="صندوق موحّد لرسائل العملاء والمتابعة." icon={MessageSquare}/><div className="fr-split"><div><DataGrid rows={filterRows(conversations)} kind="conversations" onOpen={()=>openDetail('conversations')}/></div><div className="fr-chat-preview"><MessageSquare size={42}/><h3>اختر محادثة</h3><p>التفاصيل والرسائل تظهر هنا بنفس تجربة التطبيق الجديدة.</p><button className="fr-primary" onClick={()=>openDetail('conversations')}>فتح مركز المحادثات</button></div></div></>}
    {tab==='warehouse'&&<><Header title="المخزن" sub="المنتجات والكميات والموردين بحالة واحدة واضحة." action="إضافة منتج" onAction={()=>{openNativeSection('warehouse');setTimeout(()=>nativeAction(/إضافة منتج|منتج جديد/),120)}} icon={Warehouse}/><div className="fr-metrics"><Metric icon={Package} label="المنتجات" value={products.length} sub="صنف"/><Metric icon={Warehouse} label="الموردون" value={(data.suppliers||[]).length} sub="مورد"/><Metric icon={AlertTriangle} label="مخزون منخفض" value={products.filter(o=>Number(val(o,'quantity','stock','qty')||0)<5).length} sub="يحتاج متابعة"/></div><DataGrid rows={filterRows(products)} kind="products" onOpen={()=>openDetail('warehouse')}/></>}
    {tab==='sales'&&<><Header title="المبيعات" sub="كل عمليات البيع والإيراد بتسلسل واضح." action="عملية بيع" onAction={()=>{openNativeSection('warehouse');setTimeout(()=>nativeAction(/بيع جديد|عملية بيع/),120)}} icon={ShoppingCart}/><div className="fr-metrics"><Metric icon={ShoppingCart} label="العمليات" value={sales.length} sub="عملية"/><Metric icon={DollarSign} label="الإيراد" value={`${money(revenue)} د.ع`} sub="مسجل"/></div><DataGrid rows={filterRows(sales)} kind="sales" onOpen={()=>openDetail('warehouse')}/></>}
    {tab==='debts'&&<><Header title="الديون" sub="المبالغ المفتوحة، العملاء، والمتابعة المالية." action="إضافة دين" onAction={()=>{openNativeSection('warehouse');setTimeout(()=>nativeAction(/إضافة دين|دين جديد/),120)}} icon={CreditCard}/><div className="fr-metrics"><Metric icon={CreditCard} label="السجلات" value={debts.length} sub="دين"/><Metric icon={DollarSign} label="الإجمالي" value={`${money(debtTotal)} د.ع`} sub="متبقي"/></div><DataGrid rows={filterRows(debts)} kind="debts" onOpen={()=>openDetail('warehouse')}/></>}
    {tab==='employees'&&<><Header title="الموظفون" sub="الفريق، الصلاحيات، والحالة التشغيلية." action="موظف جديد" onAction={()=>{openNativeSection('employees');setTimeout(()=>nativeAction(/إضافة موظف|موظف جديد/),120)}} icon={Users}/><DataGrid rows={filterRows(employees)} kind="employees" onOpen={()=>openDetail('employees')}/></>}
    {tab==='pages'&&<><Header title="الصفحات" sub="قنوات Facebook والربط وحالة الرسائل." action="ربط صفحة" onAction={()=>{openNativeSection('pages');setTimeout(()=>nativeAction(/ربط صفحة|إضافة صفحة/),120)}} icon={Facebook}/><DataGrid rows={filterRows(data.pages||[])} kind="pages" onOpen={()=>openDetail('pages')}/></>}
    {tab==='ai'&&<><Header title="الذكاء" sub="مركز التحكم بالردود الذكية وسلوك النظام." icon={Bot}/><div className="fr-ai-hero"><div className="fr-ai-icon"><Sparkles/></div><div><small>AI CONTROL CENTER</small><h2>الذكاء جزء من العمليات، مو شاشة إعدادات مملة.</h2><p>راقب التشغيل، افتح إعدادات الرد، وعدّل السلوك من مركز واحد.</p></div><button className="fr-primary" onClick={()=>openNativeSection('ai')}>فتح إعدادات الذكاء</button></div><div className="fr-settings-grid"><div><b>الردود الذكية</b><span>إدارة التشغيل، النبرة، وسياسات الرد.</span></div><div><b>المعالجة</b><span>متابعة تدفق الرسائل والطلبات.</span></div><div><b>الأتمتة</b><span>قواعد التنفيذ والمتابعة.</span></div></div></>}
    {tab==='stats'&&<><Header title="الإحصائيات" sub="ملخص تشغيلي ومالي موحّد لكل النظام." icon={BarChart3}/><div className="fr-metrics"><Metric icon={ClipboardList} label="الطلبات" value={orders.length} sub="إجمالي"/><Metric icon={ShoppingCart} label="المبيعات" value={sales.length} sub="عملية"/><Metric icon={DollarSign} label="الإيراد" value={`${money(revenue)} د.ع`} sub="مسجل"/><Metric icon={Users} label="الموظفون" value={employees.length} sub="فريق"/></div><div className="fr-chart"><div className="fr-bars">{[72,48,83,58,91,66,78].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div><div><b>مؤشر النشاط</b><span>عرض بصري سريع لنشاط النظام</span></div></div></>}
    {tab==='settings'&&<><Header title="الإعدادات" sub="إدارة النظام، الحساب، والتكاملات من مكان واحد." icon={Settings}/><div className="fr-settings-grid"><button onClick={()=>nativeAction(/إشعارات|الإشعارات/)}><Bell/><b>الإشعارات</b><span>التنبيهات وحالة النظام</span></button><button onClick={()=>openNativeSection('pages')}><Facebook/><b>التكاملات</b><span>Facebook والصفحات</span></button><button onClick={()=>openNativeSection('ai')}><Bot/><b>الذكاء</b><span>إعدادات الردود والأتمتة</span></button><button onClick={()=>openNativeSection('employees')}><Users/><b>المستخدمون</b><span>الموظفون والصلاحيات</span></button></div></>}
   </section>
  </main>
  {mobile&&<nav className="fr-bottom">{NAV.slice(0,5).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>select(id)}><Icon/><span>{label}</span></button>)}<button onClick={()=>setMenu(true)}><Menu/><span>المزيد</span></button></nav>}
 </div>
}
