import React,{useState}from'react';
import{Bell,Box,ChevronRight,ClipboardList,Home,Menu,MessageSquareText,MoreHorizontal,Phone,Search,Send,UserRound,Warehouse,ArrowRight,CheckCircle2,Clock3,AlertTriangle,Paperclip}from'lucide-react';
import'./mobile-radical.css';

const orders=[
{id:'1287',name:'أحمد محمد',car:'Kia Sorento 7',state:'قيد التجهيز',tone:'blue',time:'8 د',value:'85,000'},
{id:'1286',name:'سارة علي',car:'Ford Fusion',state:'جديدة',tone:'green',time:'17 د',value:'85,000'},
{id:'1285',name:'محمد حسن',car:'Kia Sorento 5',state:'بانتظار القطع',tone:'amber',time:'32 د',value:'85,000'},
{id:'1284',name:'حسين علي',car:'Toyota Camry',state:'تم التسليم',tone:'green',time:'1 س',value:'70,000'}];
const chats=[
{name:'أحمد محمد',msg:'السلام عليكم، تم اعتماد الطلب؟',time:'2 د',unread:2,order:'#1287'},
{name:'سارة علي',msg:'كم سعر فورد فيوجن؟',time:'6 د',unread:1,order:'#1286'},
{name:'محمد حسن',msg:'متى توصل القطع؟',time:'18 د',unread:0,order:'#1285'},
{name:'حسين علي',msg:'تم الاستلام، شكراً',time:'25 د',unread:0,order:'#1284'}];
function Avatar({name}){return <span className="m-avatar">{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>}
function Status({tone,children}){return <span className={'m-status '+tone}>{children}</span>}
function Top({title,back,onBack}){return <header className="m-top">{back?<button onClick={onBack} aria-label="رجوع"><ArrowRight size={21}/></button>:<div className="m-mark">ف</div>}<b>{title}</b><div className="m-actions"><button><Bell size={19}/></button><button><Search size={19}/></button></div></header>}
function HomeView({openOrder}){return <><Top title="AlFhd"/><main className="m-main"><section className="m-hero"><small>الاثنين · 24 أغسطس</small><h1>مساء الخير، فهد</h1><p>3 عناصر تحتاج قرارك الآن.</p></section><section className="m-strip"><div><small>الطلبات</small><b>1,248</b><span>+18%</span></div><div><small>قيد التنفيذ</small><b>86</b><span>+12%</span></div><div><small>جاهز</small><b>24</b><span>اليوم</span></div></section><section className="m-attention"><div className="m-sec-head"><div><small>NOW</small><h2>يحتاج انتباهك</h2></div><span className="m-live">مباشر</span></div><article className="m-alert"><AlertTriangle size={19}/><div><b>المخزون الحرج</b><p>فلتر الزيت بقي منه 4 قطع فقط.</p></div><button>فتح</button></article>{orders.slice(0,3).map(o=><button className="m-order" key={o.id} onClick={()=>openOrder(o)}><Avatar name={o.name}/><div><b>{o.name}</b><span>{o.car} · #{o.id}</span></div><Status tone={o.tone}>{o.state}</Status><ChevronRight size={17}/></button>)}</section><section className="m-flow"><div className="m-sec-head"><div><small>TODAY</small><h2>نبض اليوم</h2></div></div><div className="m-flow-row"><span><CheckCircle2 size={17}/></span><div><b>تم تسليم الطلب #1284</b><small>منذ 18 دقيقة</small></div></div><div className="m-flow-row"><span><Clock3 size={17}/></span><div><b>الطلب #1287 انتقل للتجهيز</b><small>منذ 27 دقيقة</small></div></div></section></main></>}
function OrdersView({openOrder}){const[tab,setTab]=useState('الكل');return <><Top title="الطلبات"/><main className="m-main"><div className="m-tabs">{['الكل','جديدة','التجهيز','القطع'].map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="m-search"><Search size={17}/><span>ابحث عن طلب أو سيارة...</span></div><section className="m-order-stack">{orders.concat(orders.slice(0,2)).map((o,i)=><button className="m-order-card" onClick={()=>openOrder(o)} key={o.id+i}><div className="m-order-top"><span className="m-id">#{Number(o.id)-i}</span><Status tone={o.tone}>{o.state}</Status></div><div className="m-order-person"><Avatar name={o.name}/><div><b>{o.name}</b><span>{o.car}</span></div><time>{o.time}</time></div><div className="m-order-foot"><span>تجهيز وفحص شامل</span><strong>{o.value} د.ع</strong></div></button>)}</section></main></>}
function ChatsView({openChat}){return <><Top title="المحادثات"/><main className="m-main"><div className="m-search"><Search size={17}/><span>ابحث في المحادثات...</span></div><div className="m-filterchips"><button className="on">الكل 23</button><button>غير مقروءة</button><button>مرتبطة بطلب</button></div><section className="m-chat-list">{chats.map(c=><button className="m-chat" key={c.name} onClick={()=>openChat(c)}><Avatar name={c.name}/><div><div><b>{c.name}</b><time>{c.time}</time></div><span>{c.msg}</span><small>{c.order}</small></div>{c.unread>0&&<em>{c.unread}</em>}</button>)}</section></main></>}
function ChatDetail({chat,onBack}){const[sent,setSent]=useState(false);return <div className="m-chat-screen"><Top title={chat.name} back onBack={onBack}/><button className="m-context"><ClipboardList size={18}/><div><b>{chat.order} · Kia Sorento 7</b><small>قيد التجهيز · آخر تحديث قبل 8 د</small></div><ChevronRight size={17}/></button><div className="m-messages"><span className="m-day">اليوم</span><p className="in">السلام عليكم، تم اعتماد الطلب؟<time>10:23</time></p><p className="out">وعليكم السلام، نعم تم اعتماده وبدأنا التجهيز الآن.<time>10:24</time></p><p className="in">ممتاز، شكد يحتاج وقت تقريبًا؟<time>10:25</time></p>{sent&&<p className="out">أقل من ساعة إن شاء الله، ونبلغك فور الجاهزية.<time>الآن</time></p>}</div><div className="m-composer"><button><Paperclip size={19}/></button><input placeholder="اكتب ردًا..."/><button className="send" onClick={()=>setSent(true)}><Send size={18}/></button></div></div>}
function WarehouseView(){return <><Top title="المخزن"/><main className="m-main"><section className="m-warehouse-head"><div><small>إجمالي المنتجات</small><b>684</b></div><div><small>منخفض</small><b>32</b></div><div><small>نافد</small><b>18</b></div></section><div className="m-search"><Search size={17}/><span>اسم المادة أو الرمز...</span></div><section className="m-stock">{[['زيت محرك 5W-30',120,'green'],['فلتر زيت',45,'green'],['إطارات ميشلان',18,'amber'],['بطارية 70 أمبير',7,'amber']].map(([n,q,t])=><article key={n}><div className="m-product"><Box size={28}/></div><div><b>{n}</b><small>المتوفر <strong>{q}</strong></small></div><Status tone={t}>{t==='amber'?'منخفض':'مستقر'}</Status></article>)}</section></main></>}
function OrderSheet({order,onClose}){if(!order)return null;return <div className="m-sheet-wrap" onClick={onClose}><section className="m-sheet" onClick={e=>e.stopPropagation()}><i className="m-handle"/><div className="m-sheet-head"><div><small>تفاصيل الطلب</small><b>#{order.id}</b></div><Status tone={order.tone}>{order.state}</Status></div><div className="m-car-stage"><Box size={58}/><b>{order.car}</b></div><div className="m-customer"><Avatar name={order.name}/><div><b>{order.name}</b><small>7012 123 4567</small></div><button><Phone size={18}/></button></div><dl><div><dt>نوع الطلب</dt><dd>تجهيز</dd></div><div><dt>العنوان</dt><dd>بغداد - الكرادة</dd></div><div><dt>القيمة</dt><dd>{order.value} د.ع</dd></div></dl><button className="m-primary">تحديث حالة الطلب</button></section></div>}
export default function MobilePrototype(){const[active,setActive]=useState('home');const[order,setOrder]=useState(null);const[chat,setChat]=useState(null);if(chat)return <ChatDetail chat={chat} onBack={()=>setChat(null)}/>;let view=active==='home'?<HomeView openOrder={setOrder}/>:active==='orders'?<OrdersView openOrder={setOrder}/>:active==='messages'?<ChatsView openChat={setChat}/>:<WarehouseView/>;return <div className="m-shell" dir="rtl">{view}<nav className="m-nav">{[['home','الرئيسية',Home],['messages','المحادثات',MessageSquareText],['orders','الطلبات',ClipboardList],['warehouse','المخزن',Warehouse],['more','المزيد',Menu]].map(([id,label,Icon])=><button key={id} className={active===id?'on':''} onClick={()=>id!=='more'&&setActive(id)}><Icon size={20}/><span>{label}</span></button>)}</nav><OrderSheet order={order} onClose={()=>setOrder(null)}/></div>}
