import React,{useMemo,useState}from'react';
import{Activity,Archive,BarChart3,Bell,Box,ChevronLeft,ClipboardList,Command,Filter,Home,MessageSquareText,MoreHorizontal,PackageCheck,Plus,Search,Settings,Sparkles,Users,Warehouse,Wrench,Clock3,CheckCircle2,AlertTriangle,ArrowUpLeft,Send,Paperclip,Phone,MapPin,Car,BrainCircuit,PanelLeft,ChevronDown}from'lucide-react';
import'./radical-preview.css';

const NAV=[['home','القيادة',Home],['orders','الطلبات',ClipboardList],['messages','المحادثات',MessageSquareText],['warehouse','المخزن',Warehouse],['customers','العملاء',Users],['reports','التقارير',BarChart3],['ai','الذكاء',BrainCircuit]];
const orders=[
{id:'1287',name:'أحمد محمد',car:'Kia Sorento 7',state:'قيد التجهيز',tone:'blue',time:'منذ 8 دقائق',value:'85,000',task:'فحص شامل + تجهيز'},
{id:'1286',name:'سارة علي',car:'Ford Fusion',state:'جديدة',tone:'green',time:'منذ 17 دقيقة',value:'85,000',task:'استلام وفحص أولي'},
{id:'1285',name:'محمد حسن',car:'Kia Sorento 5',state:'بانتظار القطع',tone:'amber',time:'منذ 32 دقيقة',value:'85,000',task:'صيانة نظام التعليق'},
{id:'1284',name:'حسين علي',car:'Toyota Camry',state:'تم التسليم',tone:'green',time:'منذ ساعة',value:'70,000',task:'تغيير زيت وفلاتر'}];
const events=[
{time:'10:42',title:'طلب #1287 انتقل إلى التجهيز',meta:'أحمد محمد · Kia Sorento 7',type:'progress'},
{time:'10:31',title:'تنبيه مخزون: فلتر زيت',meta:'المتوفر 4 وحدات فقط',type:'warning'},
{time:'10:18',title:'رد جديد من سارة علي',meta:'"كم سعر فورد فيوجن؟"',type:'message'},
{time:'09:54',title:'اكتمل الطلب #1284',meta:'Toyota Camry · حسين علي',type:'done'},
{time:'09:26',title:'إنشاء طلب جديد #1287',meta:'من قناة المحادثات',type:'new'}];

function Dot({tone='muted'}){return <span className={'dot '+tone}/>}
function Status({tone,children}){return <span className={'status '+tone}><Dot tone={tone}/>{children}</span>}
function Avatar({name}){return <div className="avatar">{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div>}

function Sidebar({active,setActive}){return <aside className="side"><div className="brand"><div className="mark">ف</div><div><b>AlFhd</b><small>Operations OS</small></div></div><div className="nav-label">مساحة العمل</div><nav>{NAV.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={18}/><span>{label}</span>{id==='messages'&&<em>23</em>}</button>)}</nav><div className="side-foot"><button><Settings size={18}/><span>الإعدادات</span></button><div className="profile"><Avatar name="فهد الفهداوي"/><div><b>فهد الفهداوي</b><small>المدير العام</small></div><ChevronDown size={16}/></div></div></aside>}

function Header({onSearch}){return <header className="top"><div className="context"><span className="eyebrow">الاثنين · 24 أغسطس</span><strong>مركز العمليات</strong></div><button className="search" onClick={onSearch}><Search size={17}/><span>ابحث عن طلب، عميل، سيارة...</span><kbd>⌘ K</kbd></button><div className="top-actions"><button className="icon-btn"><Bell size={18}/><i/></button><button className="icon-btn"><MessageSquareText size={18}/></button><button className="primary"><Plus size={17}/> طلب جديد</button></div></header>}

function MetricLine(){return <div className="metrics"><div><small>إجمالي الطلبات</small><b>1,248</b><span>+18%</span></div><div><small>قيد التنفيذ</small><b>86</b><span>+12%</span></div><div><small>بانتظار التجهيز</small><b>24</b><span className="down">-5%</span></div><div><small>تم التسليم</small><b>1,124</b><span>+20%</span></div><div className="sales"><small>إجمالي المبيعات</small><b>24,850,000</b><div className="spark">⌁⌁╱⌁╱╲╱╲╱⌁</div></div></div>}

function Timeline(){return <section className="timeline panel"><div className="section-head"><div><small>مباشر</small><h3>تدفق العمليات</h3></div><button className="ghost"><Filter size={15}/> تصفية</button></div><div className="stream">{events.map((e,i)=><div className="stream-row" key={i}><time>{e.time}</time><span className={'event-node '+e.type}>{e.type==='warning'?<AlertTriangle size={14}/>:e.type==='done'?<CheckCircle2 size={14}/>:e.type==='message'?<MessageSquareText size={14}/>:<Activity size={14}/>}</span><div><b>{e.title}</b><small>{e.meta}</small></div><button><MoreHorizontal size={17}/></button></div>)}</div></section>}

function LiveOrders({onSelect}){return <section className="orders panel"><div className="section-head"><div><small>التنفيذ الحالي</small><h3>طلبات تحتاج انتباه</h3></div><button className="link">عرض الكل</button></div><div className="order-list">{orders.map(o=><button className="order-row" key={o.id} onClick={()=>onSelect(o)}><Avatar name={o.name}/><div className="order-main"><div><b>{o.name}</b><small>#{o.id}</small></div><span>{o.car} · {o.task}</span></div><Status tone={o.tone}>{o.state}</Status><time>{o.time}</time><ChevronLeft size={17}/></button>)}</div></section>}

function ControlRail(){return <aside className="rail"><div className="rail-block focus"><div className="rail-title"><Sparkles size={16}/><b>موجز ذكي</b></div><p>الضغط أعلى من المعتاد في مسار التجهيز. نقل طلب واحد للمسار 3 يقلل متوسط الانتظار 18 دقيقة.</p><button>تطبيق الاقتراح</button></div><div className="rail-block"><div className="rail-title"><Clock3 size={16}/><b>جاهز للتسليم</b><span>9</span></div><div className="face-stack"><Avatar name="أحمد محمد"/><Avatar name="سارة علي"/><Avatar name="محمد حسن"/><Avatar name="حسين علي"/><i>+5</i></div><small>قيمة إجمالية 612,000 د.ع</small></div><div className="rail-block"><div className="rail-title"><Box size={16}/><b>المخزون الحرج</b><span className="warn">3</span></div><ul><li><span>فلتر زيت</span><b>4</b></li><li><span>فحمات أمامية</span><b>6</b></li><li><span>بطارية 70Ah</span><b>2</b></li></ul></div></aside>}

function HomeView({onSelect}){return <><MetricLine/><div className="command-grid"><div className="core"><Timeline/><LiveOrders onSelect={onSelect}/></div><ControlRail/></div></>}

function OrdersView({onSelect}){return <section className="workspace"><div className="page-head"><div><small>العمليات</small><h2>الطلبات</h2><p>إدارة كل طلب من الاستلام حتى التسليم.</p></div><div className="head-actions"><button className="ghost"><Filter size={16}/> الفلاتر</button><button className="primary"><Plus size={16}/> طلب جديد</button></div></div><div className="status-tabs"><button className="on">الكل <b>128</b></button><button>جديدة <b>16</b></button><button>قيد التجهيز <b>24</b></button><button>بانتظار القطع <b>7</b></button><button>تم التسليم <b>81</b></button></div><div className="table panel"><div className="thead"><span>الطلب</span><span>العميل</span><span>السيارة</span><span>الحالة</span><span>آخر تحديث</span><span>القيمة</span></div>{[...orders,...orders].map((o,i)=><button className="tr" key={i} onClick={()=>onSelect(o)}><span className="mono">#{Number(o.id)-i}</span><span><Avatar name={o.name}/><b>{o.name}</b></span><span>{o.car}</span><Status tone={o.tone}>{o.state}</Status><span>{o.time}</span><strong>{o.value}</strong></button>)}</div></section>}

function MessagesView(){const chats=['أحمد محمد','سارة علي','محمد حسن','حسين علي','نور الهادي'];return <section className="messages-layout panel"><div className="chat-list"><div className="chat-list-head"><h2>المحادثات</h2><button className="icon-btn"><Search size={17}/></button></div><div className="mini-search"><Search size={15}/><span>ابحث في المحادثات...</span></div>{chats.map((n,i)=><button className={'chat-item '+(i===0?'selected':'')} key={n}><Avatar name={n}/><div><b>{n}</b><span>{i===0?'السلام عليكم، تم اعتماد الطلب؟':'تم استلام رسالتك وسنرد قريبًا'}</span></div><time>{i===0?'2 د':'18 د'}</time>{i<2&&<em>{2-i}</em>}</button>)}</div><div className="conversation"><div className="conv-head"><Avatar name="أحمد محمد"/><div><b>أحمد محمد</b><small>متصل الآن · الطلب #1287</small></div><div><button className="icon-btn"><Phone size={17}/></button><button className="icon-btn"><MoreHorizontal size={17}/></button></div></div><div className="order-context"><Car size={17}/><div><b>Kia Sorento 7</b><small>طلب #1287 · قيد التجهيز</small></div><button>فتح الطلب <ArrowUpLeft size={14}/></button></div><div className="msgs"><span className="day">اليوم</span><p className="incoming">السلام عليكم، تم اعتماد الطلب؟<time>10:23</time></p><p className="outgoing">وعليكم السلام، نعم تم اعتماده وبدأنا التجهيز الآن.<time>10:24</time></p><p className="incoming">ممتاز، شكد يحتاج وقت تقريبًا؟<time>10:25</time></p></div><div className="composer"><button><Paperclip size={17}/></button><input placeholder="اكتب ردًا..."/><button className="send"><Send size={17}/></button></div></div></section>}

function WarehouseView(){const items=[['زيت محرك 5W-30','120','ممتاز'],['فلتر زيت','45','مستقر'],['إطارات ميشلان','18','منخفض'],['بطارية 70 أمبير','7','منخفض']];return <section className="workspace"><div className="page-head"><div><small>المخزون</small><h2>المستودع</h2><p>حالة القطع والمواد في الوقت الحقيقي.</p></div><button className="primary"><Plus size={16}/> إضافة مادة</button></div><div className="warehouse-hero"><div><small>إجمالي المنتجات</small><b>684</b></div><div><small>منخفض المخزون</small><b>32</b></div><div><small>نفد المخزون</small><b>18</b></div><div><small>قيد الطلب</small><b>7</b></div></div><div className="inventory-grid">{items.map((x,i)=><article className="inventory-card" key={x[0]}><div className="product-art">{i===0?'◉':i===1?'◎':i===2?'◍':'▣'}</div><small>المتوفر</small><strong>{x[1]}</strong><h3>{x[0]}</h3><Status tone={i>1?'amber':'green'}>{x[2]}</Status><button>عرض التفاصيل</button></article>)}</div></section>}

function GenericView({active}){const title={customers:'العملاء',reports:'التقارير والتحليلات',ai:'مركز الذكاء'}[active]||'القسم';return <section className="workspace"><div className="page-head"><div><small>AlFhd OS</small><h2>{title}</h2><p>واجهة جديدة مخصصة لهذا القسم ضمن الاتجاه التجريبي.</p></div></div><div className="generic-grid"><article className="feature-card"><Sparkles/><h3>رؤية تشغيلية أوضح</h3><p>المعلومة المهمة تظهر أولًا، بدون زحمة لوحات أو كروت مكررة.</p></article><article className="feature-card"><Activity/><h3>تحديثات مباشرة</h3><p>الأحداث والتنبيهات مرتبطة بالطلب والعميل بدل ما تكون منفصلة.</p></article><article className="feature-card"><Command/><h3>إجراءات سياقية</h3><p>كل زر يظهر بمكانه ووقته، بدون شريط أدوات محشو.</p></article></div></section>}

function OrderDrawer({order,onClose}){if(!order)return null;return <div className="drawer-wrap" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><button onClick={onClose}><ChevronLeft size={20}/></button><div><small>تفاصيل الطلب</small><b>#{order.id}</b></div><Status tone={order.tone}>{order.state}</Status></div><div className="vehicle-stage"><Car size={72}/><span>{order.car}</span></div><div className="drawer-customer"><Avatar name={order.name}/><div><b>{order.name}</b><small>7012 123 4567</small></div><button className="icon-btn"><Phone size={17}/></button></div><dl><div><dt>نوع الطلب</dt><dd>تجهيز</dd></div><div><dt>الموقع</dt><dd><MapPin size={14}/> بغداد - الكرادة</dd></div><div><dt>وقت الطلب</dt><dd>23 أغسطس · 09:26 م</dd></div><div><dt>القيمة</dt><dd>{order.value} د.ع</dd></div></dl><div className="stepper"><div className="done"><i/><span>استلام</span></div><div className="done"><i/><span>فحص</span></div><div className="current"><i/><span>تجهيز</span></div><div><i/><span>تسليم</span></div></div><button className="drawer-primary">تحديث حالة الطلب</button></aside></div>}

function MobileShell({active,setActive,onSelect}){return <div className="mobile-shell"><div className="mobile-top"><div className="brand-mini"><div className="mark">ف</div><b>AlFhd</b></div><div><button><Bell size={19}/></button><button><PanelLeft size={19}/></button></div></div><main>{active==='home'?<><div className="mobile-greeting"><span>مساء الخير 👋</span><b>فهد</b><small>نظرة سريعة على عمليات اليوم</small></div><div className="mobile-kpis"><div><small>الطلبات</small><b>1,248</b></div><div><small>جديد</small><b>86</b></div><div><small>قيد التنفيذ</small><b>24</b></div></div><div className="mobile-section"><div className="section-head"><h3>آخر الطلبات</h3><button>عرض الكل</button></div>{orders.map(o=><button className="mobile-order" key={o.id} onClick={()=>onSelect(o)}><Avatar name={o.name}/><div><b>{o.name}</b><small>{o.car}</small></div><Status tone={o.tone}>{o.state}</Status></button>)}</div></>:active==='messages'?<MessagesView/>:active==='warehouse'?<WarehouseView/>:<OrdersView onSelect={onSelect}/>}</main><nav className="mobile-nav">{[['home','الرئيسية',Home],['messages','المحادثات',MessageSquareText],['orders','الطلبات',ClipboardList],['warehouse','المخزن',Box],['more','المزيد',MoreHorizontal]].map(([id,l,I])=>{const Icon=I;return <button key={id} className={active===id?'on':''} onClick={()=>setActive(id==='more'?'orders':id)}><Icon size={20}/><span>{l}</span></button>})}</nav></div>}

export default function RadicalPrototype(){const[active,setActive]=useState('home');const[selected,setSelected]=useState(null);const[search,setSearch]=useState(false);const isMobile=useMemo(()=>typeof window!=='undefined'&&window.innerWidth<760,[]);if(isMobile)return <><MobileShell active={active} setActive={setActive} onSelect={setSelected}/><OrderDrawer order={selected} onClose={()=>setSelected(null)}/></>;let view=active==='home'?<HomeView onSelect={setSelected}/>:active==='orders'?<OrdersView onSelect={setSelected}/>:active==='messages'?<MessagesView/>:active==='warehouse'?<WarehouseView/>:<GenericView active={active}/>;return <div className="os"><Sidebar active={active} setActive={setActive}/><div className="app"><Header onSearch={()=>setSearch(true)}/><main className="content">{view}</main></div><OrderDrawer order={selected} onClose={()=>setSelected(null)}/>{search&&<div className="search-overlay" onClick={()=>setSearch(false)}><div className="command-palette" onClick={e=>e.stopPropagation()}><Search size={20}/><input autoFocus placeholder="ابحث في كل AlFhd..."/><kbd>ESC</kbd><div className="search-results"><small>نتائج سريعة</small><button onClick={()=>{setActive('orders');setSearch(false)}}><ClipboardList size={17}/><div><b>الطلب #1287</b><span>أحمد محمد · Kia Sorento 7</span></div></button><button onClick={()=>{setActive('warehouse');setSearch(false)}}><Box size={17}/><div><b>فلتر زيت</b><span>المتوفر 45 قطعة</span></div></button></div></div></div>}</div>}
